// react_frontend/src/components/SurveyList/SurveyList.tsx
import React, { useState, useEffect } from 'react';
import { useNavigate, Link } from 'react-router-dom';
import surveyService from '../../services/surveyService';
import { Survey } from '../../models/Survey';
import './SurveyList.css';

const SurveyList: React.FC = () => {
  const navigate = useNavigate();
  const [surveys, setSurveys] = useState<Survey[]>([]);
  const [loading, setLoading] = useState<boolean>(true);

  useEffect(() => {
    loadSurveys();
  }, []);

  const loadSurveys = async (): Promise<void> => {
    setLoading(true);
    try {
      const data = await surveyService.getAllSurveys();
      setSurveys(data);
      setLoading(false);
    } catch (error) {
      console.error('Error loading surveys:', error);
      setLoading(false);
      alert('Failed to load surveys. Please make sure the backend is running.');
    }
  };

  const editSurvey = (id: number | undefined): void => {
    if (id) {
      navigate(`/survey/${id}`);
    }
  };

  const deleteSurvey = async (id: number | undefined): Promise<void> => {
    if (!id) return;

    if (window.confirm('Are you sure you want to delete this survey?')) {
      try {
        await surveyService.deleteSurvey(id);
        loadSurveys();
      } catch (error) {
        console.error('Error deleting survey:', error);
        alert('Failed to delete survey');
      }
    }
  };

  const getLikedItems = (survey: Survey): string => {
    const liked: string[] = [];
    if (survey.likedStudents) liked.push('Students');
    if (survey.likedLocation) liked.push('Location');
    if (survey.likedCampus) liked.push('Campus');
    if (survey.likedAtmosphere) liked.push('Atmosphere');
    if (survey.likedDormRooms) liked.push('Dorm Rooms');
    if (survey.likedSports) liked.push('Sports');
    return liked.length > 0 ? liked.join(', ') : 'None';
  };

  const formatDate = (dateString: string): string => {
    if (!dateString) return '';
    const date = new Date(dateString);
    return date.toLocaleDateString('en-US', {
      year: 'numeric',
      month: '2-digit',
      day: '2-digit'
    });
  };

  return (
    <div className="container mt-4">
      <div className="d-flex justify-content-between align-items-center mb-4">
        <h2>All Surveys</h2>
        <Link to="/survey" className="btn btn-primary">New Survey</Link>
      </div>

      {loading && (
        <div className="text-center my-5">
          <div className="spinner-border text-primary" role="status">
            <span className="visually-hidden">Loading...</span>
          </div>
        </div>
      )}

      {!loading && surveys.length === 0 && (
        <div className="alert alert-info" role="alert">
          No surveys found. <Link to="/survey" className="alert-link">Create your first survey</Link>
        </div>
      )}

      {!loading && surveys.length > 0 && (
        <div className="card">
          <div className="card-body">
            <div className="table-responsive">
              <table className="table table-striped table-hover">
                <thead>
                  <tr>
                    <th>ID</th>
                    <th>Name</th>
                    <th>Email</th>
                    <th>Date</th>
                    <th>Liked Most</th>
                    <th>Interest Source</th>
                    <th>Recommendation</th>
                    <th>Actions</th>
                  </tr>
                </thead>
                <tbody>
                  {surveys.map((survey) => (
                    <tr key={survey.id}>
                      <td>{survey.id}</td>
                      <td>{survey.firstName} {survey.lastName}</td>
                      <td>{survey.email}</td>
                      <td>{formatDate(survey.dateOfSurvey)}</td>
                      <td>{getLikedItems(survey)}</td>
                      <td>{survey.interestSource}</td>
                      <td>{survey.recommendationLikelihood}</td>
                      <td>
                        <div className="btn-group btn-group-sm" role="group">
                          <button
                            type="button"
                            className="btn btn-outline-primary"
                            onClick={() => editSurvey(survey.id)}
                            title="Edit"
                          >
                            Edit
                          </button>
                          <button
                            type="button"
                            className="btn btn-outline-danger"
                            onClick={() => deleteSurvey(survey.id)}
                            title="Delete"
                          >
                            Delete
                          </button>
                        </div>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>

            <div className="mt-3 text-muted">
              Total Surveys: {surveys.length}
            </div>
          </div>
        </div>
      )}

      <div className="text-center mt-4 mb-5">
        <Link to="/" className="text-muted">Back to Home</Link>
      </div>
    </div>
  );
};

export default SurveyList;

// frontend/student-survey-app/src/app/components/survey-list/survey-list.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Router, RouterModule } from '@angular/router';
import { SurveyService } from '../../services/survey.service';
import { Survey } from '../../models/survey.model';

/**
 * Survey List component for displaying all surveys in a table.
 * Provides functionality to view, update, and delete surveys.
 */
@Component({
  selector: 'app-survey-list',
  standalone: true,
  imports: [CommonModule, RouterModule],
  templateUrl: './survey-list.component.html',
  styleUrls: ['./survey-list.component.css']
})
export class SurveyListComponent implements OnInit {
  surveys: Survey[] = [];
  loading = true;

  constructor(
    private surveyService: SurveyService,
    private router: Router
  ) { }

  ngOnInit(): void {
    this.loadSurveys();
  }

  /**
   * Load all surveys from the backend
   */
  loadSurveys(): void {
    this.loading = true;
    this.surveyService.getAllSurveys().subscribe({
      next: (data) => {
        this.surveys = data;
        this.loading = false;
      },
      error: (error) => {
        console.error('Error loading surveys:', error);
        this.loading = false;
        alert('Failed to load surveys. Please make sure the backend is running.');
      }
    });
  }

  /**
   * Navigate to edit survey form
   */
  editSurvey(id: number | undefined): void {
    if (id) {
      this.router.navigate(['/survey', id]);
    }
  }

  /**
   * Delete a survey with confirmation
   */
  deleteSurvey(id: number | undefined): void {
    if (!id) return;

    if (confirm('Are you sure you want to delete this survey?')) {
      this.surveyService.deleteSurvey(id).subscribe({
        next: () => {
          this.loadSurveys(); // Reload the list
        },
        error: (error) => {
          console.error('Error deleting survey:', error);
          alert('Failed to delete survey');
        }
      });
    }
  }

  /**
   * Get liked items as comma-separated string
   */
  getLikedItems(survey: Survey): string {
    const liked: string[] = [];
    if (survey.likedStudents) liked.push('Students');
    if (survey.likedLocation) liked.push('Location');
    if (survey.likedCampus) liked.push('Campus');
    if (survey.likedAtmosphere) liked.push('Atmosphere');
    if (survey.likedDormRooms) liked.push('Dorm Rooms');
    if (survey.likedSports) liked.push('Sports');
    return liked.length > 0 ? liked.join(', ') : 'None';
  }
}

<div class="container mt-4">
  <!-- Header -->
  <div class="d-flex justify-content-between align-items-center mb-4">
    <h2>All Surveys</h2>
    <a routerLink="/survey" class="btn btn-primary">New Survey</a>
  </div>

  <!-- Loading Spinner -->
  <div *ngIf="loading" class="text-center my-5">
    <div class="spinner-border text-primary" role="status">
      <span class="visually-hidden">Loading...</span>
    </div>
  </div>

  <!-- No Surveys Message -->
  <div *ngIf="!loading && surveys.length === 0" class="alert alert-info" role="alert">
    No surveys found. <a routerLink="/survey" class="alert-link">Create your first survey</a>
  </div>

  <!-- Surveys Table -->
  <div *ngIf="!loading && surveys.length > 0" class="card">
    <div class="card-body">
      <div class="table-responsive">
        <table class="table table-striped table-hover">
          <thead>
            <tr>
              <th>ID</th>
              <th>Name</th>
              <th>Email</th>
              <th>Date</th>
              <th>Liked Most</th>
              <th>Interest Source</th>
              <th>Recommendation</th>
              <th>Actions</th>
            </tr>
          </thead>
          <tbody>
            <tr *ngFor="let survey of surveys">
              <td>{{ survey.id }}</td>
              <td>{{ survey.firstName }} {{ survey.lastName }}</td>
              <td>{{ survey.email }}</td>
              <td>{{ survey.dateOfSurvey | date: 'MM/dd/yyyy' }}</td>
              <td>{{ getLikedItems(survey) }}</td>
              <td>{{ survey.interestSource }}</td>
              <td>{{ survey.recommendationLikelihood }}</td>
              <td>
                <div class="btn-group btn-group-sm" role="group">
                  <button type="button" class="btn btn-outline-primary" (click)="editSurvey(survey.id)" title="Edit">
                    Edit
                  </button>
                  <button type="button" class="btn btn-outline-danger" (click)="deleteSurvey(survey.id)" title="Delete">
                    Delete
                  </button>
                </div>
              </td>
            </tr>
          </tbody>
        </table>
      </div>

      <div class="mt-3 text-muted">
        Total Surveys: {{ surveys.length }}
      </div>
    </div>
  </div>

  <!-- Back to Home Link -->
  <div class="text-center mt-4 mb-5">
    <a routerLink="/" class="text-muted">Back to Home</a>
  </div>
</div>
